# Numpy execises

Selected exercises from
https://www.machinelearningplus.com/python/101-numpy-exercises-python/

In [2]:
import numpy as np

1. Create a 1D array of numbers from 0 to 9


In [3]:
# Expected output
#> array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


2. Create a 3×3 numpy array of all True’s

3. Extract all odd numbers from arr


In [6]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#> array([1, 3, 5, 7, 9])

4. Replace all odd numbers in arr with -1


In [10]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#>  array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])


5. Replace all odd numbers in arr with -1 in a new output without changing arr


In [22]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
# Expected output
#>  arr array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])
#>  output array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

6. Convert a 1D array to a 2D array with 2 rows


In [25]:
arr = np.arange(10)
# Expected output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9]])

7. Stack arrays a and b vertically


In [33]:
a = np.arange(10).reshape(2,5)
b = np.ones([2,5])

In [34]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [35]:
b

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# Expected output
#> array([[0, 1, 2, 3, 4],
#>        [5, 6, 7, 8, 9],
#>        [1, 1, 1, 1, 1],
#>        [1, 1, 1, 1, 1]])


8. Stack the arrays a and b horizontally.

In [40]:
a = np.arange(10).reshape(2,5)
b = np.ones([2,5])

In [41]:
# Expected output
#> array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
#>        [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

9. Get the positions where elements of a and b match

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [45]:
# Expected output
#> (array([1, 3, 5, 7]),)

10. Get all items between 5 and 10 from a.

In [47]:
a = np.array([2, 6, 1, 9, 10, 3, 27])

In [48]:
# Expected output
#>(array([6, 9, 10]),)

11. Find the mean, median, standard deviation of iris's sepallength (1st column)

In [62]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [63]:
iris

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa'],
       [b'5.4', b'3.7', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.4', b'1.6', b'0.2', b'Iris-setosa'],
       [b'4.8', b'3.0', b'1.4', b'0.1', b'Iris-setosa'],
       [b'4.3', b'3.0', b'1.1', b'0.1', b'Iris-setosa'],
       [b'5.8', b'4.0', b'1.2', b'0.2', b'Iris-setosa'],
       [b'5.7', b'4.4', b'1.5', b'0.4', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.3', b'0.4', b'Iris-setosa'],
       [b'5.1', b'3.5', b'1.4',

12. Create a normalized form of iris's sepallength whose values range exactly between 0 and 1 so that the minimum has value 0 and maximum has value 1.

In [68]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

13. Find the number and position of missing values in iris_2d's sepallength (1st column)

In [77]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20), ] = np.nan

14. Filter the rows of iris_2d that has petallength (3rd column) > 1.5 and sepallength (1st column) < 5.0

In [81]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

15. Find out if iris_2d has any missing values.

In [83]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

16. Replace all occurrences of nan with 0 in numpy array

In [85]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
iris_2d[np.random.randint(150, size=20), np.random.randint(4, size=20)] = np.nan

In [86]:
iris_2d

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [nan, 3. , 1.1, 0.1],
       [5.8, nan, 1.2, 0.2],
       [5.7, 4.4, 1.5, nan],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [nan, 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, nan],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

17. Create a new column for volume in iris_2d, where volume is (pi x petallength x sepal_length^2)/3

In [91]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3,4])
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')#only to identify the columns

18. Find the most frequent value of petal length (3rd column) in iris dataset.

In [107]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

19. From the array a, replace all values greater than 30 to 30 and less than 10 to 10.

In [112]:
np.random.seed(100)
a = np.random.uniform(1,50, 20)

In [113]:
a

array([27.62684215, 14.64009987, 21.80136195, 42.39403048,  1.23122395,
        6.95688692, 33.86670515, 41.466785  ,  7.69862289, 29.17957314,
       44.67477576, 11.25090398, 10.08108276,  6.31046763, 11.76517714,
       48.95256545, 40.77247431,  9.42510962, 40.99501269, 14.42961361])

20.  Drop all nan values from a 1D numpy array

In [117]:
np.array([1,2,3,np.nan,5,6,7,np.nan])

array([ 1.,  2.,  3., nan,  5.,  6.,  7., nan])

In [118]:
#Expected output
# array([ 1.,  2.,  3.,  5.,  6.,  7.])