# Scikit-Learn

- Scikit-Learn is a package that provides efficient versions of a large number of common ML algorithms. 
- Scikit-Learn is characterized by a clean, uniform, and streamlined API, as well as by very useful and complete online documentation.
- A benefit of this uniformity is that once you understand the basic use and syntax of Scikit-Learn for one type of model, switching to a new model or algorithm is very straightforward.


## Data Representation in Scikit-Learn

- The information can be thought of as a two-dimensional numerical array, the features matrix. 
- By convention, this matrix is stored in a variable named X. 
- The features matrix is assumed to be two-dimensional, with shape [n_samples, n_features], and is most often contained in a NumPy array or a Pandas DataFrame.
    - The samples (i.e., rows) always refer to the individual objects described by the dataset.
    - The features (i.e., columns) refer to the distinct observations that describe each sample in a quantitative manner.

## Target array
- The target array, called y,  is usually one dimensional, with length n_samples, and is generally contained in a NumPy array or Pandas Series. 
- The target array may have continuous numerical values, or discrete classes/labels. 
- The target array is that it is usually the quantity we want to predict from the data.




## Scikit-Learn’s Estimator API

### Estimators objects
- An estimator is any object that learns from data
    - it may be a classification, regression or clustering algorithm or a transformer that extracts/filters useful features from raw data.
- Fitting data: the main API implemented by scikit-learn is that of the estimator.;
    - All estimator objects expose a fit method that takes a dataset (usually a 2-d array):
    
<tt> >>> estimator.fit(data)</tt>

- Estimator parameters: All the parameters of an estimator can be set when it is instantiated or by modifying the corresponding attribute:

<tt> >>> estimator = Estimator(param1=1, param2=2) </tt>
- Estimated parameters: When data is fitted with an estimator, parameters are estimated from the data at hand. All the estimated parameters are attributes of the estimator object ending by an underscore:
    
    <tt> >>> estimator.estimated_param_ </tt>


In [1]:
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [2]:
import sklearn as sk

In [3]:
from sklearn import datasets

In [4]:
iris = datasets.load_iris()

In [5]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [6]:
X = iris.data

In [7]:
y =iris.target

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
X

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [10]:
from sklearn.neighbors import KNeighborsClassifier

In [11]:
knn = KNeighborsClassifier()

In [12]:
knn.fit(X,y)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [13]:
knn.predict(X)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
len(X)

In [14]:
knn.fit(X[:100],y[:100])

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [15]:
knn.predict(X[100:])

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [16]:
result=knn.predict(X[100:])

In [17]:
y[100:]-result

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1])

In [18]:
unique, counts = np.unique((y[100:]-result), return_counts=True) 
dict(zip(unique, counts))

{1: 50}

In [19]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [20]:
indice =np.random.permutation(len(X))

In [21]:
indice

array([ 86, 128,  26,   5,  78, 143,  23,  12,  94, 121,  39, 103,  65,
       136, 129, 137,  33,  90,  59, 144, 149, 126,   4,  51,  57,   2,
       131,  91,  71,  15,   6,  82,  41,  36,  55,  72, 102, 135,  18,
       123,  79,  22, 112,  89,  80,  60, 122,  17,  43, 146, 147,  56,
        37,  99,  38,   8,  85, 105,   3,  63, 120,  34,  61, 117,  68,
         7, 106,  81,  44, 104,  95,  87,  29,  58,  30, 132,  75, 140,
        40,  48,  84,  76,  77, 115,  49, 139, 100, 118,  69,  16, 108,
        93,  54, 111,  92,  28,  10,  50,   9,  66,  96, 141,  83,  46,
        31,  73, 119,  97, 138,  88, 116,  27,  42, 113, 124,  24,  11,
        14, 148,   0,  52,  32,  64,  70, 110,   1,  98, 101,  53, 145,
       109,  74,  25,  62, 130, 127, 125, 107, 142,  13,  45, 114,  20,
        47,  67,  35,  21,  19, 134, 133])

In [22]:
X_train= X[indice[:100]]
y_train= y[indice[:100]]
X_test= X[indice[100:]]
y_test= y[indice[100:]]

In [23]:
y_train

array([1, 2, 0, 0, 1, 2, 0, 0, 1, 2, 0, 2, 1, 2, 2, 2, 0, 1, 1, 2, 2, 2,
       0, 1, 1, 0, 2, 1, 1, 0, 0, 1, 0, 0, 1, 1, 2, 2, 0, 2, 1, 0, 2, 1,
       1, 1, 2, 0, 0, 2, 2, 1, 0, 1, 0, 0, 1, 2, 0, 1, 2, 0, 1, 2, 1, 0,
       2, 1, 0, 2, 1, 1, 0, 1, 0, 2, 1, 2, 0, 0, 1, 1, 1, 2, 0, 2, 2, 2,
       1, 0, 2, 1, 1, 2, 1, 0, 0, 1, 0, 1])

In [28]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [29]:
result=knn.predict(X_test)

In [30]:
y_test - result

array([ 0,  0, -1,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0])

In [31]:
unique, counts = np.unique((y_test-result), return_counts=True) 
dict(zip(unique, counts))

{-1: 1, 0: 48, 1: 1}

In [37]:
knn = KNeighborsClassifier(n_neighbors=10)

In [38]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=10, p=2,
                     weights='uniform')

In [39]:
result=knn.predict(X_test)

In [40]:
result

array([1, 2, 2, 0, 0, 1, 1, 1, 1, 1, 2, 0, 0, 2, 2, 0, 0, 0, 2, 0, 1, 0,
       1, 1, 2, 0, 1, 2, 1, 2, 2, 1, 0, 1, 2, 2, 2, 2, 2, 0, 0, 2, 0, 0,
       1, 0, 0, 0, 2, 1])

In [41]:
unique, counts = np.unique((y_test-result), return_counts=True) 
dict(zip(unique, counts))

{-1: 1, 0: 46, 1: 3}

In [42]:
from sklearn.tree import DecisionTreeClassifier

In [43]:
dtc = DecisionTreeClassifier()

In [44]:
dtc.fit(X_train,y_train)
result=dtc.predict(X_test)

In [45]:
y_test - result

array([ 0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0, -1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,
        0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  1])

In [46]:
unique, counts = np.unique((y_test-result), return_counts=True) 
dict(zip(unique, counts))

{-1: 1, 0: 47, 1: 2}

## 1) creare un dataframe che contenga i valori di iris
## 2) creare due nuovin attributi che rappresentano l'area del petalo e del sepalo
## 3) utilizzare il nuovo dataframe per fare la predizione
## 4) utilizzare un classificatore non ancora introdotto (bayes?)